import os
os.system("sudo pacman -S base-devel curl git gperf help2man unzip wget")
os.system("sudo pacman -S curl sed libarchive nettle")
os.system("sudo pacman -S meson gtk2")
print("setting up koxtoolchain")
os.system("git clone --recursive --depth=1 https://github.com/koreader/koxtoolchain.git")
os.chdir("koxtoolchain")
os.system("chmod +x gen-tc.sh")
print("What moddle kindle do you want to build for:")
print("TC	         Supported Devices	                             Target")
print("kindle        Kindle 2, DX, DXg, 3                           [not supported by this tutorial]")
print("kindle5       Kindle 4, Touch, PW1                           [not supported by this tutorial]")
print("kindlepw2	 Kindle PW2 & everything since on FW <5.16.3	kindlepw2")
print("kindlehf	     Any Kindle on FW >= 5.16.3	                    kindlehf")
target = input(">>> ")
os.system("./gen-tc.sh " + target)
print("Do you want the SDK")
print("The KMC Kindle SDK augments your existing koxtoolchain installation by providing headers and library files used with the Kindle.")
choice = input("(y/n) >>> ")
if choice == "y":
    os.system("git clone --recursive --depth=1 https://github.com/KindleModding/kindle-sdk.git")
    os.chdir("kindle-sdk")
    os.system("chmod +x gen-sdk.sh")
    os.system("./gen-sdk.sh " + target)
    print("Once the SDK has finished installing itself, make a note of the path it returns to the meson-crosscompile.txt file, this will be important later!")
    print("A file will be created in your kindle-build-environment directory to keep note of this file")
    directory = input("please enter the path it returned to the meson-crosscompile.txt file >>> ")
    os.system('echo "' + directory +'" > meson-crosscompile-directory.txt')
    os.system('cp meson-crosscompile-directory.txt ~')
print("the environment is set up go to https://kindlemodding.org/kindle-dev/gtk-tutorial/setting-up.html to learn how to create a project")
print("to enter your enviroment in the future type distrobox enter kindle-build-env in your terminal")
